spring.application.name=cityv
server.port=9090

# ---- Supabase Postgres (pooler connection) ----
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.gyeuqiijmzmumixgzqlg
spring.datasource.password=LkWyZoDRC7OZ3s4K
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---- File upload size limits ----
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ---- Supabase Storage ----
supabase.url=https://gyeuqiijmzmumixgzqlg.supabase.co
supabase.service-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZXVxaWlqbXptdW1peGd6cWxnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODQxNzk5MCwiZXhwIjoyMTAzOTkzOTkwfQ.shkwaNbc8qEeIkC9D33AHsn67Af-hdGC9goTDOCX9zM
supabase.bucket=complaints

# Password Fordet
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fazlerabbicse65@gmail.com
spring.mail.password=wjsvypbjlfpxirpi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000